language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t simoncar/docker-react -f Dockerfile.dev .  # f means force to use and -t instead tag

script:
  - docker run -e CI=true simoncar/docker-react npm run test