language: generic

services:
  - docker

before_install:
  - docker_build -t ssccar/docker-react -f Dockerfile.dev .

# thanks to -- --coverage tests will exit otherwise they hang forever
script:
  - docker run -e CI=true simoncar/docker-react npm run test

